### ISSUE TITLE
Info Wordlistctrl 

### ISSUE THREAD

**Issue by IvanDeFelice76** [BlackArch/wordlistctl#1]
Can this work on Fedora 29?

**Comment by sepehrdaddev** [comment]
@xzj8b3  This has never been tested on fedora but since it's in pure python probably yes,
but I will test it on the Fedora 29 (just to be sure) and let you know.

**Comment by IvanDeFelice76** [comment]
Thank you very much because it is a great tool

**Comment by sepehrdaddev** [comment]
@xzj8b3 I have tested it, unfortunately I couldn't get libtorrent-rasterbar to work.
:(
