### ISSUE TITLE
Add support for wildcard/keyword fetching

### ISSUE THREAD

**Issue by bitshiftnetau** [BlackArch/wordlistctl#18]
Would be fantastic to simply enter a keyword and download all wordlists that match that word.

**Example**

If I search for "subdomains":

`wordlistctl search subdomains`
```
--==[ wordlistctl by blackarch.org ]==--

    0 > bitquark-subdomains-top100000 (1.43 Mb)
    1 > shubs-subdomains (5.98 Mb)
    2 > subdomains-top1million-110000 (1.12 Mb)
    3 > subdomains-top1million-20000 (148.83 Kb)
    4 > subdomains-top1million-5000 (33.66 Kb)
    5 > assetnote_httparchive_subdomains_2020_11_18 (29.78 Mb)
    6 > assetnote_2m-subdomains (29.40 Mb)

```

I should be able to then use that same syntax to then fetch all of these wordlists. 

`wordlistctl fetch subdomains
`

Having to specify the full name of each wordlist when fetching is a real buzzkill and doesn't provide a unified user experience between search and fetch.

**Comment by aancw** [comment]
Nice idea

**Comment by aancw** [comment]
Btw, for search there is already available flag for that, it's search_term

**Comment by bitshiftnetau** [comment]
Oh... really? It seems to work without the flag as well 😅

**Comment by aancw** [comment]
Yep it's set by default.

**Comment by aancw** [comment]
Done. Will be pushing it to master. It's what you mean?
![image](https://user-images.githubusercontent.com/6284204/116607345-10ddf880-a95c-11eb-9d8c-5034c09ac5d3.png)

**Comment by bitshiftnetau** [comment]
Whoa... nice! Yeh that's awesome! You're awesome!

**Comment by aancw** [comment]
Try to update it with `git clone https://github.com/BlackArch/wordlistctl` before releasing to BA repo.

**Comment by bitshiftnetau** [comment]
Yep just tested on Arch base... works just fine. Looking forward to seeing this downstream!

**Comment by aancw** [comment]
Thanks for your suggestion. I will close this issue.
