### ISSUE TITLE
Issue with module 'collections'

### ISSUE THREAD

**Issue by frobodaggins** [BlackArch/wordlistctl#23]
[-] module 'collections' has no attribute 'MutableMapping'

Might be my fault due to an extra package i installed and didn't notice it would conflict with wordlistctl. But I thought i would mention this just in case it's not just me being a nub. Thanks for everything you guys do. Y'all are true heros.

**Comment by ikstream** [comment]
Please provide steps so we can reproduce your issue.
You installed `wordlistctl` and just run it without any parameter?

**Comment by ikstream** [comment]
As there was no feedback, I am closing this issue
