### ISSUE TITLE
Seclists filenames changed

### ISSUE THREAD

**Issue by insomnes** [BlackArch/wordlistctl#3]
Hello!
Have problem with https://github.com/danielmiessler/SecLists/blob/master/Discovery/DNS/subdomains-top1million-5000.txt
Cause name has changed, wordlistctl has wrong downloading link now.

**Comment by noraj** [comment]
Also now GitHub redirects `https://github.com/danielmiessler/SecLists/raw/master/` to `https://raw.githubusercontent.com/danielmiessler/SecLists/master/` we should do a big sed on that.

**Comment by noraj** [comment]
From `https://github.com/danielmiessler/SecLists/raw/master/Discovery/DNS/subdomains-top1mil-5000.txt` to `https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/DNS/subdomains-top1million-5000.txt`

The entry to change in config is

```
      {
        "name": "subdomains-top1mil-5000.txt",
        "url": [
          "https://github.com/danielmiessler/SecLists/raw/master/Discovery/DNS/subdomains-top1mil-5000.txt"
        ],
        "sum": [
          "3cf063b94f036c9a70f2409bdda0898e"
        ],
        "size": [
          33660,
          33660
        ]
      },
```
