### ISSUE TITLE
wordlistctl fetch comes back with error

### ISSUE THREAD

**Issue by takov751** [BlackArch/wordlistctl#8]
wordlistctl v0.8.8

I installed it from the repo recently . whenever i try to fetch a wordlist this is the response.:
`--==[ wordlistctl by blackarch.org ]==--

usage: wordlistctl [-h] [-v] {fetch,search,list} ...
wordlistctl: error: unrecognized arguments: tripple
`
So basically i am able to download the wordlist manually getting the link from the repo.json
Nice project by the way

**Comment by takov751** [comment]
Nevermind . I read the code nice straightforward job. Meaningless bug report. Thank you for this useful tool

**Comment by EmilienMottet** [comment]
Use 
`wordlistctl fetch -l tripple`
